apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-express-app
  namespace: argocd
spec: 
  project: default

  source: 
    repoURL: https://github.com/tka4roman/mongo-charts.git
    targetRevision: HEAD
    path: mongo
  destination:
    server: https://kubernetes.default.svc
    namespace: mongo
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true

  automated: 
    selfHeal: true
    prune: true
